#dev  配置文件
server:
  port: 1012

spring:
  cloud:
    config:
      label: master
      server:
        default-application-name: config-server
        git:
         uri: https://github.com/ChenRunPing/ms-configServer
         search-paths: ms-congfigServer

