#dev  配置文件
server:
  port: 1012

spring:
  cloud:
    config:
      server:
        default-application-name: config-server
        default-label: master
        git:
         uri: https://github.com/ChenRunPing
         search-paths: ms-congfigServer

